# Generated by Django 3.0 on 2021-01-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='foodimage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
