# Generated by Django 3.1.7 on 2021-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210123_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='manjeet', max_length=70),
            preserve_default=False,
        ),
    ]
